<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const p = new Promise((resolve, reject) => {
            // resolve('用户数据')

            reject('失败')
        })

        // await 要放在 async 函数中,后面要放一个 Promise 对象
        // await 返回 Promise 对象的值
        // await 通过 try...catch 捕获 Promise 对象状态为失败的值
        async function main() {
            try {
                let result = await p
                console.log(result);
            } catch (e) {
                console.log(e);
            }
        }
        main()
    </script>

</body>

</html>